# Generated by Django 2.2.12 on 2020-04-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=16, default=0, max_digits=64)),
                ('betting', models.DecimalField(decimal_places=16, default=0, max_digits=64)),
                ('gains', models.DecimalField(decimal_places=16, default=0, max_digits=64)),
                ('address', models.CharField(max_length=64)),
                ('account_name', models.CharField(max_length=64)),
                ('application_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_pot', models.DecimalField(decimal_places=16, default=0, max_digits=64)),
                ('total_nano_transferred', models.DecimalField(decimal_places=16, default=0, max_digits=64)),
                ('total_transactions', models.DecimalField(decimal_places=16, default=0, max_digits=64)),
                ('application_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_account', models.CharField(max_length=64)),
                ('from_account', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=16, default=0, max_digits=64)),
                ('application_name', models.CharField(max_length=64)),
            ],
        ),
    ]
