# Generated by Django 2.2.12 on 2020-04-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nano_poker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestate',
            name='current_pot',
        ),
    ]
