# Generated by Django 2.2.12 on 2020-04-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nano_poker', '0002_remove_gamestate_current_pot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=64)),
                ('policy_name', models.CharField(max_length=64)),
                ('executed_time', models.DateTimeField(default=None, null=True)),
                ('application_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='executed_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=65),
        ),
    ]
