# Generated by Django 2.2.12 on 2020-04-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nano_poker', '0004_auto_20200429_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='application_name',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='from_account',
            new_name='transaction_hash_receiving',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='to_account',
            new_name='transaction_hash_sending',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='executed_time',
        ),
        migrations.AddField(
            model_name='transaction',
            name='complete',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='error',
            field=models.CharField(default=None, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='timestamp',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
